### ISSUE TITLE
How do I change the folder location?

### ISSUE THREAD

**Issue by viasbox** [samirelanduk/tiktok-save#10]
I don't know which file and which line to edit to make the "./save.py" commands work & the previous threads to this haven't been answered. I'd appreciate a clear answer to this, as I'm sure it'd help other laymen too.
My current directory is "E:\backups\tiktok\liked" ; the data.json file is inside it, and i execute the commands in git bash as an admin, so I think the folder is the only problem. the error command is: "bash: ./save.py: No such file or directory"

**Comment by samirelanduk** [comment]
You need to be in the directory of tiktok-save itself (whereever you saved it), and then give "E:\backups\tiktok\liked" as the third argument. I'll update the README to be clearer.
