### ISSUE TITLE
Problems to save saved and bookmarked videos

### ISSUE THREAD

**Issue by FrankTheReal** [samirelanduk/tiktok-save#2]
Hello.

I followed the installation instruction, and now I wanted to save the video from the user_data.json

 But sadly when I run this command, I get this error:

C:\Users\themf\tiktok-save>save.py bookmarked user_data.json bookmarked

C:\Users\themf\tiktok-save>
[main 2021-12-25T13:55:26.345Z] update#setState idle
[main 2021-12-25T13:55:26.400Z] ExtensionHostStarterWorker created
[main 2021-12-25T13:55:27.141Z] Starting extension host with pid 8064 (fork() took 10 ms).
[main 2021-12-25T13:55:56.347Z] update#setState checking for updates
[main 2021-12-25T13:55:56.379Z] update#setState idle
[18980:1225/145726.114:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled

Can you please help me?

![image](https://user-images.githubusercontent.com/81906489/147386681-ca8b8612-1273-47d7-99cd-c6f5c4f49b9e.png)

**Comment by SoLwmon** [comment]
What was the solution to this problem?
