### ISSUE TITLE
Save exact time and date from TikTok JSON as filename in .mp4 file

### ISSUE THREAD

**Issue by Txxicer** [samirelanduk/tiktok-save#5]
Well, im not so good in programming with python, i tried much but it fails every time. I wanna change the program that the full date and time is save as filename in the file. So for example "YYYY_MM_DD HH.MM.SS_TikTokID -> 2022_01_01 00.02.23_584739857"

Is it possible that you can implement this function?

**Comment by samirelanduk** [comment]
Yes, I like this idea - I've added it.
