### ISSUE TITLE
Folder location

### ISSUE THREAD

**Issue by rahali2000** [samirelanduk/tiktok-save#6]
Hi, 

I’ve tried running this utility but each time I do so this issue pops up:

FileNotFoundError: [Errno 2] No such file or directory: 'liked_videos_path'

I have zero experience with python so it’s probably an issue on my part than the utility itself. I’ve tried moving  around the liked and bookmarked videos folders but I still get the error. Here are the file locations for reference:

<img width="347" alt="Screen Shot 2022-11-21 at 10 42 22 pm" src="https://user-images.githubusercontent.com/117913321/203043222-fbddd014-893a-43de-b1e3-92895a60f7db.png">

Any help would be greatly appreciated. Thank you!

**Comment by samirelanduk** [comment]
'liked_videos_path' is just an example folder name - you have to give it the path of an actual folder on your computer where the files will be saved to. In this case there isn't a folder called liked_videos_path.
